# Generated by Django 5.2.1 on 2025-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='data do lançamento', verbose_name='Data do lançamento')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='última atualização', verbose_name='Data da última atualização')),
                ('descricao', models.CharField(help_text='Descrição da Transação', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da Transação', max_digits=10, verbose_name='Valor')),
                ('tipo_transacao', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], help_text='receita ou despesa', max_length=1, verbose_name='Tipo de Transacao')),
                ('status', models.CharField(choices=[('E', 'Efetivado'), ('P', 'Pendente')], help_text='Pendente ou Efetivado', max_length=1, verbose_name='Status da Transacao')),
                ('data_transacao', models.DateField(help_text='xx/xx/xxxx', verbose_name='Data de Transacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
